#!/usr/bin/env python3
"""
Pack/unpack the oversized patch payloads that can't go into git as-is.

    ./tools/assets.py status     what is oversized, what is packed
    ./tools/assets.py pack       compress everything >=50MB into <name>.xz
    ./tools/assets.py unpack     restore the raw files from the .xz siblings
    ./tools/assets.py untrack    drop packed raw payloads from the git index

Run `pack` after dropping a new big blob into patches/, then commit the .xz --
the raw file is gitignored. Fresh clones don't need `unpack`; the build
extracts what it needs on demand.
"""

import argparse
import io
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from assets import (  # noqa: E402
    THRESHOLD,
    archive_exists,
    archive_files,
    archive_size,
    compress,
    decompress,
    find_oversized,
    find_packed,
    packed_path,
    raw_path,
)

DEFAULT_ROOTS = ["patches"]
GITHUB_LIMIT = 100 * 1024 * 1024

GITIGNORE = ".gitignore"
BEGIN = (
    "# BEGIN packed-assets (generated by tools/assets.py pack -- do not edit by hand)"
)
END = "# END packed-assets"


def packed_in(roots):
    return sorted({p for r in roots for p in find_packed(r)})


def git_path(archive):
    return raw_path(archive).replace(os.sep, "/")


def update_gitignore(roots):
    """
    Rewrite the managed .gitignore block so every packed payload has its raw
    file ignored. The .xz stays tracked; the raw one is a build artifact.

    Regenerated on each `pack`, so adding a new big blob needs no hand-editing.
    """
    if not os.path.exists(GITIGNORE):
        return 0

    raw = sorted({git_path(p) for p in packed_in(roots)})
    block = [BEGIN] + [f"/{p}" for p in raw] + [END]

    with io.open(GITIGNORE, encoding="utf-8") as f:
        lines = f.read().split("\n")
    if BEGIN in lines and END in lines:
        head, tail = lines[: lines.index(BEGIN)], lines[lines.index(END) + 1 :]
    else:
        head, tail = lines, []
        while head and head[-1] == "":
            head.pop()
        head.append("")

    with io.open(GITIGNORE, "w", encoding="utf-8") as f:
        f.write("\n".join(head + block + tail))
    return len(raw)


def mb(n):
    return f"{n / 1024 / 1024:.1f}M"


def collect_roots(roots):
    return [r for r in (roots or DEFAULT_ROOTS) if os.path.exists(r)]


def cmd_status(args):
    roots = collect_roots(args.roots)
    oversized = [p for r in roots for p in find_oversized(r, args.threshold)]
    packed = packed_in(roots)

    # archive_exists, not os.path.exists: a split archive has no .xz itself.
    unpacked = [p for p in oversized if not archive_exists(packed_path(p))]

    print(f"threshold: {mb(args.threshold)}\n")

    print(f"packed archives ({len(packed)}):")
    saved = 0
    for p in packed:
        raw = raw_path(p)
        here = os.path.exists(raw)
        rawsz = os.path.getsize(raw) if here else 0
        if here:
            saved += rawsz - archive_size(p)
        shards = len(archive_files(p))
        parts = f"  [{shards} parts]" if shards > 1 else ""
        state = f"  (extracted: {mb(rawsz)})" if here else "  (not extracted)"
        print(f"  {mb(archive_size(p)):>8}  {p}{parts}{state}")
    if saved:
        print(f"\n  saved vs raw: {mb(saved)}")

    print(f"\noversized and NOT packed ({len(unpacked)}):")
    for p in sorted(unpacked):
        too_big = os.path.getsize(p) > GITHUB_LIMIT
        flag = "  << over GitHub's 100MB limit" if too_big else ""
        print(f"  {mb(os.path.getsize(p)):>8}  {p}{flag}")
    if not unpacked:
        print("  (none -- nothing would be rejected on push)")

    stale = tracked_raw(packed)
    if stale:
        print(f"\nstill tracked by git despite being packed ({len(stale)}):")
        for p in stale:
            print(f"  {p}")
        print(
            "  .gitignore does not apply to tracked files -- run:"
            "\n    ./tools/assets.py untrack"
        )
    return 1 if (unpacked or stale) else 0


def cmd_pack(args):
    roots = collect_roots(args.roots)
    targets = sorted({p for r in roots for p in find_oversized(r, args.threshold)})
    if not targets:
        print("nothing over threshold")
        return 0

    print(f"packing {len(targets)} file(s) >= {mb(args.threshold)}\n")

    def one(p):
        before = os.path.getsize(p)
        out = compress(p, force=args.force)
        if out is None:
            return p, before, None
        # compress() may have split it, so the .xz itself can be gone.
        return p, before, archive_size(out)

    total_before = total_after = 0
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for p, before, after in pool.map(one, targets):
            if after is None:
                print(f"  skip  {mb(before):>8}           {p}  (up to date)")
                continue
            total_before += before
            total_after += after
            print(f"  ok    {mb(before):>8} -> {mb(after):>8}  {p}")

    if total_before:
        print(
            f"\n{mb(total_before)} -> {mb(total_after)} "
            f"({100 * total_after / total_before:.0f}% of original)"
        )
    stale = tracked_raw(packed_in(roots))
    n = update_gitignore(roots)
    print(f"\n{GITIGNORE}: {n} raw payload(s) listed in the packed-assets block")
    print("Commit the .xz files; the raw payloads stay gitignored.")
    if stale:
        print(
            f"\nWARNING: {len(stale)} raw payload(s) are still tracked "
            "by git -- .gitignore\ndoes not apply to tracked files. "
            "Run: ./tools/assets.py untrack"
        )
    return 0


def cmd_unpack(args):
    roots = collect_roots(args.roots)
    targets = packed_in(roots)
    if not targets:
        print("nothing packed")
        return 0

    print(f"unpacking {len(targets)} archive(s)\n")

    def one(p):
        out = decompress(raw_path(p), force=args.force)
        return p, out

    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for p, out in pool.map(one, targets):
            if out is None:
                print(f"  skip  {raw_path(p)}  (already extracted)")
            else:
                print(f"  ok    {mb(os.path.getsize(out)):>8}  {out}")
    return 0


def tracked_raw(archives):
    """Packed payloads whose raw file git still tracks."""
    out = subprocess.run(["git", "ls-files", "-z"], capture_output=True)
    if out.returncode != 0:
        return []
    tracked = set(out.stdout.decode("utf-8", "replace").split("\0"))
    return sorted(p for p in map(git_path, archives) if p in tracked)


def cmd_untrack(args):
    """Drop packed raw payloads from the index, keeping them on disk."""
    roots = collect_roots(args.roots)
    stale = tracked_raw(packed_in(roots))
    if not stale:
        print("nothing to untrack")
        return 0

    print(
        f"removing {len(stale)} raw payload(s) from the git index "
        "(files stay on disk):\n"
    )
    for p in stale:
        print(f"  {p}")
    cmd = ["git", "rm", "--cached", "--quiet", "--"] + stale
    rc = subprocess.run(cmd).returncode
    if rc != 0:
        print("\ngit rm failed")
        return rc
    print("\nDone. Commit the removals together with the .xz files.")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("command", choices=["status", "pack", "unpack", "untrack"])
    ap.add_argument(
        "roots",
        nargs="*",
        help=f"directories to walk (default: {' '.join(DEFAULT_ROOTS)})",
    )
    ap.add_argument(
        "-t",
        "--threshold",
        type=lambda v: int(float(v) * 1024 * 1024),
        default=THRESHOLD,
        metavar="MB",
        help="size cutoff in MB (default: 50)",
    )
    ap.add_argument(
        "-j", "--jobs", type=int, default=max(1, (os.cpu_count() or 2) // 2)
    )
    ap.add_argument(
        "-f", "--force", action="store_true", help="redo even if up to date"
    )
    args = ap.parse_args()

    return {
        "status": cmd_status,
        "pack": cmd_pack,
        "unpack": cmd_unpack,
        "untrack": cmd_untrack,
    }[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
